import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import React from 'react';
import HeaderLayout from "@/components/HeaderLayout";
import FooterLayout from "@/components/FooterLayout";
import styles from '@/styles/layout.module.scss'

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
          <HeaderLayout/>
          <div className={styles.container}>
            {children}
          </div>
          <FooterLayout/>
      </body>
    </html>
  );
}
