import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import React from 'react';
import HeaderLayout from "@/app/components/HeaderLayout";
import FooterLayout from "@/app/components/FooterLayout";
import styles from '@/app/styles/layout.module.scss'
import AuthProvider from "@/app/context/AuthProvider";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/*<body className={inter.className}>*/}
      {/*  <AuthProvider>*/}
      {/*    <HeaderLayout/>*/}
      {/*    <div className={styles.container}>*/}
            {children}
      {/*    </div>*/}
      {/*    <FooterLayout/>*/}
      {/*  </AuthProvider>*/}
      {/*</body>*/}
    </html>
  );
}
