// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  feature: dynamic(() => import("./Feature")),
  hero: dynamic(() => import("./Hero")),
  testimonial: dynamic(() => import("./Testimonial")),
  text_width_image: dynamic(() => import("./TextWidthImage")),
};
