// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  feature: dynamic(() => import("./Feature")),
  hero: dynamic(() => import("./Hero")),
  recuitment: dynamic(() => import("./Recuitment")),
  testimonial: dynamic(() => import("./Testimonial")),
  text_width_image: dynamic(() => import("./TextWidthImage")),
};
